Repository NeuralEnsemble/elephant, pull requests merged in 2018-10, with the labels that each got.

#150 Function for wavelet transform
  elephant/signal_processing.py
  elephant/test/test_signal_processing.py
Labels: data analysis

#183 added missing doc pages
  doc/modules.rst
  doc/reference/cell_assembly_detection.rst
  doc/reference/spade.rst
Labels: documentation, enhancement

#176 Added option to spade to use a 3-dimensional pattern spectrum to test
  elephant/spade.py
  elephant/test/test_spade.py
Labels: enhancement

#184 Sorting of modules names
  doc/conf.py
  doc/modules.rst
  doc/reference/asset.rst
  doc/reference/cell_assembly_detection.rst
  doc/reference/conversion.rst
  doc/reference/cubic.rst
  doc/reference/current_source_density.rst
  doc/reference/kernels.rst
  doc/reference/neo_tools.rst
  doc/reference/pandas_bridge.rst
  doc/reference/signal_processing.rst
  doc/reference/spade.rst
  doc/reference/spectral.rst
  doc/reference/spike_train_correlation.rst
  doc/reference/spike_train_dissimilarity.rst
  doc/reference/spike_train_generation.rst
  doc/reference/spike_train_surrogates.rst
  doc/reference/sta.rst
  doc/reference/statistics.rst
  doc/reference/unitary_event_analysis.rst
Labels: documentation, enhancement, question
