Repository NeuralEnsemble/elephant, pull requests merged in 2019-04, with the labels that each got.

#205 Removes static dependencies on readthedocs envioronment file conflicting with readthedocs.org
  doc/environment.yml
Labels: bug, documentation

#204 Changes for compatibility release 0.6.1
  LICENSE.txt
  README.rst
  doc/authors.rst
  doc/conf.py
  doc/install.rst
  doc/release_notes.rst
  elephant/__init__.py
  setup.py
Labels: enhancement

#171 Added check for empty spike train in corrcoef
  elephant/spike_train_correlation.py
  elephant/test/test_spike_train_correlation.py
Labels: enhancement

#211 Corrected improper use of .base on quantities objects
  elephant/spike_train_generation.py
  elephant/test/test_spike_train_generation.py
Labels: bug

#213 Fix setup.py not installing the fast FIM module for Windows machines
  elephant/spade.py
  setup.py
Labels: bug

#217 Changed setup.py to not crash when fim.so download is unavailable for some reason
  setup.py
Labels: bug
