Repository NeuralEnsemble/elephant, pull requests merged in 2020-09, with the labels that each got.

#339 Feature/inhomogeneous gamma
  elephant/spike_train_generation.py
  elephant/test/test_spike_train_generation.py
Labels: new functionality

#345 Added information on citing Elephant to documentation, fixed bib entries
  CITATION.txt
  MANIFEST.in
  README.md
  doc/bib/elephant.bib
  doc/citation.rst
  doc/index.rst
  elephant/asset.py
Labels: documentation, enhancement

#343 Three surrogate methods: Trial-shifting, Bin Shuffling, ISI dithering
  doc/tutorials/statistics.ipynb
  elephant/spade.py
  elephant/spike_train_surrogates.py
  elephant/test/test_spade.py
  elephant/test/test_spike_train_surrogates.py
Labels: enhancement, new functionality

#332 Time-domain pairwise Granger causality
  .gitignore
  doc/authors.rst
  doc/bib/elephant.bib
  doc/modules.rst
  doc/reference/causality.rst
  elephant/causality/__init__.py
  elephant/causality/granger.py
  elephant/test/test_causality.py
Labels: new functionality

#346 [Feature] Add revised local variability LvR
  elephant/statistics.py
  elephant/test/test_statistics.py
Labels: enhancement, new functionality
