Repository NeuralEnsemble/elephant, pull requests merged in 2020-11, with the labels that each got.

#372 optimized zscore
  elephant/signal_processing.py
  elephant/test/test_signal_processing.py
  elephant/utils.py
Labels: optimization

#373 added normalization in time_histogram analogsignal annotations
  elephant/statistics.py
  elephant/test/test_statistics.py
Labels: enhancement

#371 don't sort the input array in ISI
  elephant/statistics.py
  elephant/test/test_statistics.py
Labels: enhancement, optimization

#370 waveform_snr accepts waveforms directly instead of a spiketrain
  elephant/test/test_waveform_features.py
  elephant/waveform_features.py
Labels: enhancement

#368 faster BinnedSpikeTrain with a bugfix for n_discarded
  elephant/cell_assembly_detection.py
  elephant/conversion.py
  elephant/spade.py
  elephant/spike_train_correlation.py
  elephant/statistics.py
  elephant/test/test_conversion.py
  elephant/utils.py
Labels: breaking-changes, bugifx, optimization

#362 Faster instantaneous rate with a bugfix (rate wasn't centered)
  .travis.yml
  elephant/kernels.py
  elephant/statistics.py
  elephant/test/test_spike_train_generation.py
  elephant/test/test_statistics.py
  requirements/requirements-tests.txt
Labels: breaking-changes, bugifx, optimization

#376 provenance tracking in cch output
  elephant/conversion.py
  elephant/spike_train_correlation.py
  elephant/statistics.py
  elephant/test/test_spike_train_correlation.py
  elephant/utils.py
Labels: enhancement

#378 unit-less BinnedSpikeTrain
  elephant/conversion.py
  elephant/spike_train_correlation.py
  elephant/spike_train_surrogates.py
  elephant/statistics.py
  elephant/test/test_conversion.py
  elephant/test/test_spike_train_correlation.py
  elephant/utils.py
Labels: optimization

#358 vectorized Current Source Density 'generate_lfp' function
  elephant/current_source_density.py
Labels: optimization

#380 fixed warnings in time_histogram function
  elephant/conversion.py
  elephant/statistics.py
  elephant/utils.py
Labels: bugifx, enhancement

#359 Feature/conditional granger
  elephant/causality/granger.py
  elephant/test/test_causality.py
Labels: new functionality
