Repository NeuralEnsemble/elephant, pull requests merged in 2022-03, with the labels that each got.

#454 Add a function to discretise spiketimes
  elephant/conversion.py
  elephant/test/test_conversion.py
Labels: new functionality

#447 Support SpikeTrainList object and deprecate RecordingChannel in Elephant
  elephant/conversion.py
  elephant/current_source_density.py
  elephant/spade.py
  elephant/spike_train_synchrony.py
  elephant/statistics.py
  elephant/test/test_conversion.py
  elephant/test/test_kcsd.py
  elephant/test/test_spade.py
  elephant/utils.py
  requirements/requirements.txt
Labels: bugfix

#459 Enh/add zenodo json
  .zenodo.json
  doc/acknowledgments.rst
  doc/authors.rst
Labels: enhancement, help wanted

#456 Enh/add dois to documentation
  doc/citation.rst
  doc/tutorials.rst
Labels: documentation

#414 Boundary correction rate for firing rate estimator with Gaussian KDE
  .travis.yml
  elephant/statistics.py
  elephant/test/test_spade.py
  elephant/test/test_statistics.py
Labels: bugfix

#460 Neo v0.10.0, remove support for python 3.6
  .github/workflows/CI.yml
  .github/workflows/build_wheels.yml
  .travis.yml
  doc/install.rst
  requirements/environment-docs.yml
  requirements/environment-tests.yml
  requirements/environment.yml
  setup.py
Labels: bug, Neo related, build, bugfix

#441 Fix/update tutorials asset and unitary_event_analysis to use nixio 1.5.0
  doc/tutorials/asset.ipynb
  doc/tutorials/unitary_event_analysis.ipynb
  requirements/environment-docs.yml
  requirements/requirements-tutorials.txt
Labels: Neo related, documentation, breaking-changes

#463 Enh/elephant data versioning
  doc/tutorials/asset.ipynb
  doc/tutorials/gpfa.ipynb
  doc/tutorials/granger_causality.ipynb
  doc/tutorials/parallel.ipynb
  doc/tutorials/statistics.ipynb
  doc/tutorials/unitary_event_analysis.ipynb
  elephant/datasets.py
  elephant/test/download.py
  elephant/test/test_spectral.py
  elephant/test/test_spike_train_synchrony.py
  elephant/test/test_unitary_event_analysis.py
Labels: enhancement, new functionality, breaking-changes

#452 This is housekeeping in preparation of a release 0.11.0
  .travis.yml
  LICENSE.txt
  README.md
  doc/conf.py
  doc/maintainers_guide.rst
  doc/release_notes.rst
  doc/tutorials/gpfa.ipynb
  elephant/VERSION
  elephant/__init__.py
  elephant/causality/granger.py
  elephant/conversion.py
  elephant/cubic.py
  elephant/gpfa/gpfa.py
  elephant/gpfa/gpfa_core.py
  elephant/gpfa/gpfa_util.py
  elephant/kernels.py
  elephant/neo_tools.py
  elephant/pandas_bridge.py
  elephant/parallel/__init__.py
  elephant/phase_analysis.py
  elephant/signal_processing.py
  elephant/spade.py
  elephant/spectral.py
  elephant/spike_train_correlation.py
  elephant/spike_train_dissimilarity.py
  elephant/spike_train_generation.py
  elephant/spike_train_surrogates.py
  elephant/spike_train_synchrony.py
  elephant/sta.py
  elephant/statistics.py
  elephant/test/test_asset.py
  elephant/test/test_causality.py
  elephant/test/test_conversion.py
  elephant/test/test_cubic.py
  elephant/test/test_gpfa.py
  elephant/test/test_kernels.py
  elephant/test/test_neo_tools.py
  elephant/test/test_pandas_bridge.py
  elephant/test/test_phase_analysis.py
  elephant/test/test_signal_processing.py
  elephant/test/test_spade.py
  elephant/test/test_spectral.py
  elephant/test/test_spike_train_correlation.py
  elephant/test/test_spike_train_dissimilarity.py
  elephant/test/test_spike_train_generation.py
  elephant/test/test_spike_train_surrogates.py
  elephant/test/test_sta.py
  elephant/test/test_statistics.py
  elephant/test/test_unitary_event_analysis.py
  elephant/test/test_waveform_features.py
  elephant/unitary_event_analysis.py
  elephant/waveform_features.py
  setup.py
Labels: enhancement

#438 Improvement of Spike Time Tiling Coefficient (STTC)
  elephant/spike_train_correlation.py
Labels: optimization
