Repository NeuralEnsemble/elephant, pull requests merged in 2022-02, with the labels that each got.

#444 updated spade tutorial to work with viziphant 0.2.0 (#88)
  doc/tutorials/spade.ipynb
Labels: bugfix

#417 Feature/multitaper psd estimate
  elephant/spectral.py
  elephant/test/test_spectral.py
Labels: new functionality

#457 Revert "Feature/multitaper psd estimate"
  elephant/spectral.py
  elephant/test/test_spectral.py
Labels: documentation
