Repository NeuralEnsemble/elephant, pull requests merged in 2022-11, with the labels that each got.

#524 Fix: zenodo.json
  .zenodo.json
Labels: bugfix

#522 Fix/CI: update deprecated actions and commands
  .github/workflows/CI.yml
Labels: build

#527 Fix: math rendering with sphinx 5.3.0
  doc/conf.py
Labels: bugfix, build html

#531 Add multitaper_psd to documentation
  elephant/spectral.py
Labels: documentation
