Repository NeuralEnsemble/elephant, pull requests merged in 2022-04, with the labels that each got.

#468 added example to docstring, removed reference to annotations
  elephant/asset/asset.py
  elephant/conversion.py
  elephant/test/test_icsd.py
Labels: documentation, bugfix

#474 Fix/asset on mac os, add CI workflow for macOS
  .github/workflows/CI.yml
  elephant/asset/asset.py
  requirements/environment-tests.yml
  setup.py
Labels: bug, build, bugfix

#482 Fix/spike train dissimilarity
  elephant/test/test_spike_train_dissimilarity.py
Labels: enhancement

#483 Fixed MANIFEST.in to include CUDA/OpenCL sources when installing
  MANIFEST.in
Labels: bugfix
