Repository NeuralEnsemble/elephant, pull requests merged in 2023-07, with the labels that each got.

#532 [ENH] add shield for twitter and fosstodon
  README.md
Labels: enhancement

#553 Fix/docstring warnings 2
  elephant/phase_analysis.py
  elephant/spectral.py
Labels: documentation

#554 Fix complexity for binary=False and spread=0
  elephant/statistics.py
  elephant/test/test_statistics.py
Labels: bugfix

#576 [Fix] cell assembly detection
  elephant/cell_assembly_detection.py
Labels: bugfix

#572 [Fix] Use default tolerances for np.testing.allclose() in WPLI ground truth test
  elephant/test/test_phase_analysis.py
Labels: bugfix

#573 [ENH] Use numpy assert array equal in test_multitaper_cohere_perfect_cohere
  .gitignore
  elephant/spectral.py
  elephant/test/test_spectral.py
  requirements/requirements.txt
Labels: enhancement

#577 Release 0.13.0
  .zenodo.json
  codemeta.json
  doc/release_notes.rst
  elephant/VERSION
Labels: maintenance
