Repository NeuralEnsemble/elephant, pull requests merged in 2023-02, with the labels that each got.

#535 Fix/numpy >= 1.24.0
  elephant/cell_assembly_detection.py
  elephant/current_source_density.py
  elephant/current_source_density_src/KCSD.py
  elephant/current_source_density_src/utility_functions.py
  elephant/gpfa/gpfa_core.py
  elephant/gpfa/gpfa_util.py
  elephant/phase_analysis.py
  elephant/signal_processing.py
  elephant/test/test_conversion.py
  elephant/test/test_neo_tools.py
  elephant/test/test_spade.py
  elephant/test/test_unitary_event_analysis.py
  requirements/environment-docs.yml
  requirements/environment-tests.yml
  requirements/environment.yml
  requirements/requirements.txt
Labels: bugfix

#523 Fix documentation, remove version cap on sphinxcontrib-bibtex
  .github/workflows/CI.yml
  doc/citation.rst
  doc/conf.py
  doc/contribute.rst
  doc/reference/_spike_train_processing.rst
  doc/reference/asset.rst
  doc/reference/causality.rst
  doc/reference/cell_assembly_detection.rst
  doc/reference/change_point_detection.rst
  doc/reference/cubic.rst
  doc/reference/gpfa.rst
  doc/reference/signal_processing.rst
  doc/reference/spade.rst
  doc/reference/spike_train_surrogates.rst
  doc/reference/unitary_event_analysis.rst
  doc/reference/waveform_features.rst
  elephant/spike_train_generation.py
  elephant/statistics.py
  requirements/requirements-docs.txt
Labels: documentation, build html

#534 Fix/update elephant logo
  doc/conf.py
  doc/images/elephant_logo.png
  doc/images/elephant_logo_sidebar.png
Labels: documentation

#478 Fix/docstring warnings
  doc/_templates/autosummary/gpfa_class.rst
  doc/_templates/autosummary/spike_train_generation_class.rst
  doc/conf.py
  doc/install.rst
  elephant/asset/asset.py
  elephant/causality/granger.py
  elephant/cell_assembly_detection.py
  elephant/conversion.py
  elephant/current_source_density.py
  elephant/datasets.py
  elephant/gpfa/gpfa.py
  elephant/signal_processing.py
  elephant/spade.py
  elephant/spike_train_correlation.py
  elephant/spike_train_generation.py
  elephant/spike_train_surrogates.py
  elephant/spike_train_synchrony.py
  elephant/unitary_event_analysis.py
Labels: documentation

#503 Enh/add doctest runner
  .github/workflows/CI.yml
  elephant/spade.py
Labels: documentation

#542 Update to quantities >0.14.0
  requirements/requirements.txt
Labels: bug, bugfix

#538 add "try it on ebrains" button for elephant tutorials
  doc/tutorials.rst
Labels: documentation

#411 Feature WPLI
  .gitignore
  doc/bib/elephant.bib
  elephant/phase_analysis.py
  elephant/test/test_phase_analysis.py
Labels: enhancement

#525 Feature/multitaper cross spectrum
  elephant/spectral.py
  elephant/test/test_spectral.py
Labels: new functionality
