Repository NeuralEnsemble/elephant, pull requests merged in 2023-10, with the labels that each got.

#587 [MAIN] Fix typos and grammatical errors in GPFA tutorial
  doc/tutorials/gpfa.ipynb
Labels: maintenance

#595 [Fix] skip multitaper unittest for new numpy version 1.26.0
  elephant/test/test_spectral.py
Labels: bugfix

#596 [Doc] readthedocs: configuration key build.image is deprecated, changed to build.os
  doc/tutorials/unitary_event_analysis.ipynb
  readthedocs.yml
Labels: build html

#592 [Fix] z score inplace
  elephant/signal_processing.py
  elephant/test/test_signal_processing.py
Labels: bugfix

#598 [MAIN] Fix CI conda runner
  .github/workflows/CI.yml
Labels: maintenance

#585 [ENH] Added ASSET class initialization parameter to define the binning rounding error tolerance
  elephant/asset/asset.py
  elephant/test/test_asset.py
Labels: enhancement

#582 [MAIN] update build_wheels action
  .github/workflows/build_wheels.yml
Labels: maintenance

#570 [ENH] Improved output messages/status information of ASSET functions
  elephant/asset/asset.py
  elephant/test/test_asset.py
Labels: enhancement

#564 [Fix] spike time tiling coefficient for unsorted spiketrains, added validation test
  doc/bib/elephant.bib
  elephant/spike_train_correlation.py
  elephant/test/test_spike_train_correlation.py
Labels: bugfix

#579 [Feature] Trial handling in Elephant
  doc/_templates/autosummary/trials_class.rst
  doc/modules.rst
  doc/reference/trials.rst
  elephant/__init__.py
  elephant/statistics.py
  elephant/test/test_statistics.py
  elephant/test/test_trials.py
  elephant/trials.py
Labels: new functionality
