Repository NeuralEnsemble/elephant, pull requests merged in 2023-06, with the labels that each got.

#545 Feature/spectral granger
  doc/bib/elephant.bib
  elephant/causality/granger.py
  elephant/test/test_causality.py
Labels: new functionality

#549 Added functions to extract time bin and neuron information from SSEs obtained using ASSET
  elephant/asset/asset.py
  elephant/test/test_asset.py
Labels: enhancement

#556 Multitaper psd segmentation
  elephant/spectral.py
  elephant/test/test_spectral.py
Labels: enhancement

#547 Fix old references to elephant-data in the code
  elephant/datasets.py
Labels: documentation, bugfix

#575 Fixed bug in spade, linked to missing call of min_neu, added test
  doc/conf.py
  elephant/spade.py
  elephant/test/test_spade.py
  requirements/requirements.txt
Labels: bugfix
