Repository NeuralEnsemble/elephant, pull requests merged in 2023-11, with the labels that each got.

#530 Feature/remove pandas bridge
  doc/modules.rst
  doc/reference/pandas_bridge.rst
  elephant/pandas_bridge.py
  elephant/test/test_pandas_bridge.py
  requirements/environment-docs.yml
  requirements/environment-tests.yml
  requirements/environment.yml
  requirements/requirements-extras.txt
Labels: breaking-changes

#488 [Main] remove deprecated features
  doc/tutorials/spade.ipynb
  doc/tutorials/statistics.ipynb
  doc/tutorials/unitary_event_analysis.ipynb
  elephant/cell_assembly_detection.py
  elephant/change_point_detection.py
  elephant/conversion.py
  elephant/cubic.py
  elephant/current_source_density.py
  elephant/gpfa/gpfa.py
  elephant/gpfa/gpfa_util.py
  elephant/kernels.py
  elephant/neo_tools.py
  elephant/signal_processing.py
  elephant/spade.py
  elephant/spectral.py
  elephant/spike_train_correlation.py
  elephant/spike_train_dissimilarity.py
  elephant/spike_train_generation.py
  elephant/statistics.py
  elephant/test/test_current_source_density.py
  elephant/test/test_gpfa.py
  elephant/test/test_parallel.py
  elephant/test/test_signal_processing.py
  elephant/test/test_spectral.py
  elephant/test/test_spike_train_correlation.py
  elephant/test/test_spike_train_dissimilarity.py
  elephant/test/test_spike_train_generation.py
  elephant/unitary_event_analysis.py
Labels: breaking-changes

#601 Release 1.0.0
  .zenodo.json
  codemeta.json
  doc/release_notes.rst
  elephant/VERSION
Labels: maintenance

#607 Added a section in the documentation linking to Alpaca.
  doc/index.rst
Labels: documentation
