Repository NeuralEnsemble/elephant, pull requests merged in 2024-03, with the labels that each got.

#611 [MAIN] add Python 3.12
  .github/workflows/CI.yml
  .github/workflows/build_wheels.yml
  doc/install.rst
Labels: maintenance

#617 [FIX] failing unitests for neo_tools with Neo 0.13.0
  elephant/spike_train_synchrony.py
  elephant/test/test_neo_tools.py
Labels: Neo related

#560 [Feature] Merging "Total spiking probability edges" into elephant
  .zenodo.json
  doc/authors.rst
  doc/bib/elephant.bib
  doc/modules.rst
  doc/reference/functional_connectivity_estimation.rst
  elephant/functional_connectivity.py
  elephant/functional_connectivity_src/total_spiking_probability_edges.py
  elephant/test/test_total_spiking_probability_edges.py
Labels: new functionality

#622 Add documentation fixes to TSPE
  elephant/functional_connectivity.py
  elephant/functional_connectivity_src/total_spiking_probability_edges.py
Labels: documentation
